-- 코드를 입력하세요
SELECT TITLE, T1.BOARD_ID, REPLY_ID, T2.WRITER_ID, T2.CONTENTS, DATE_FORMAT(T2.CREATED_DATE, '%Y-%m-%d') CREATE_DATE
FROM USED_GOODS_BOARD T1 INNER JOIN USED_GOODS_REPLY T2 ON T1.BOARD_ID = T2.BOARD_ID
WHERE YEAR(T1.CREATED_DATE) = 2022 AND MONTH(T1.CREATED_DATE) = 10
ORDER BY T2.CREATED_DATE ASC, T1.TITLE ASC;